version: '3.4'

services:
  messagingapp.api:
    image: messagingapp/api
    container_name: messagingapp.api
    build:
      context: .
      dockerfile: MessagingApp.Api/Dockerfile
      labels:
        - messagingapp.api.development
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      CONNECTIONSTRINGS__DBCONNECTION: Server=messagingapp.database;Port=5432;Database=${POSTGRES_DB};User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      DBPROVIDER: Postgres
      TZ: Asia/Dubai
    ports:
      - "7500:80"
    volumes:
      - $APPDATA\ASP.NET\Https:/root/.aspnet/https:ro
      - $APPDATA\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
    
  messagingapp.database:
    image: postgres:14-alpine
    container_name: messagingapp.database
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - TZ=Asia/Dubai
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgresdata:
