FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["MessagingApp.Api/MessagingApp.Api.csproj", "MessagingApp.Api/"]
COPY ["MessagingApp.Infrastructure/MessagingApp.Infrastructure.csproj", "MessagingApp.Infrastructure/"]
RUN dotnet restore "MessagingApp.Api/MessagingApp.Api.csproj"
COPY . .
WORKDIR "/src/MessagingApp.Api"
RUN dotnet build "MessagingApp.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MessagingApp.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MessagingApp.Api.dll"]
